package Server;


/**
* Server/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Friday, December 5, 2014 7:28:19 PM UTC
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
