package Server;


/**
* Server/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Friday, December 5, 2014 7:28:19 PM UTC
*/

public interface HelloOperations 
{
  boolean open (String filename);
  void request (String filename, String requesteeIP);
  String transfer (String filename);
  boolean modifyRecord (int record, String newRecord);
  String readRecord (int recordNum);
  boolean changeActiveFile (String newFileName);
  void getResponse (int statusCode, String responseIP);
  void startConnectWeb ();
} // interface HelloOperations
