package Server;


/**
* Server/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Saturday, December 6, 2014 4:23:12 AM GMT
*/

public interface HelloOperations 
{
  boolean open (String filename);
  void request (String filename, String requesteeIP);
  String transfer (String filename);
  boolean modifyRecord (int record, String newRecord);
  String readRecord (int recordNum);
  boolean changeActiveFile (String newFileName);
  void getResponse (int statusCode, String responseIP);
  void startConnectWeb ();
  void ping ();
  String getIP ();
} // interface HelloOperations
