package Server;


/**
* Server/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Tuesday, December 2, 2014 1:59:47 AM GMT
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
