package Server;


/**
* Server/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Thursday, December 11, 2014 3:01:59 AM GMT
*/

public interface HelloOperations 
{
  boolean open (String filename, int key);
  void request (String filename, String requesteeIP, int key);
  String transfer (String filename);
  boolean modifyRecord (int record, String newRecord, int key);
  String readRecord (int recordNum, int key);
  boolean changeActiveFile (String newFileName, int key);
  void getResponse (int statusCode, String responseIP, int key);
  void startConnectWeb ();
  void ping ();
  String getIP ();
  String getLocalFiles ();
  String getAllKnownFiles ();
  void sendDeleteSignal (String filename, int key);
  void deleteFile (String filename, String requestee);
  void clientQuit (int key);
} // interface HelloOperations
